"""Independent exhaustive-subset oracle generated by TypeScript rules."""
import json
from pathlib import Path
import sys
import unittest
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from fabledan.cards import order_of
from fabledan.combos import gen_moves, PASS
from app_adapter import TYPES


def signature(cards):
    return tuple(sorted(c%54 for c in cards))

def key(pattern,level):
    t=TYPES[pattern['type']]; p=pattern['primaryRank']
    if t in (5,9): return p-4
    if t==6: return p-2
    if t==7: return p-1
    if t==10: return 0
    r=level if p==15 else {14:0,16:13,17:14}.get(p,p-1)
    return order_of(r,level)

class RuleParityTests(unittest.TestCase):
    def test_exhaustive_small_hand_subsets(self):
        data=json.loads((Path(__file__).resolve().parents[1]/'fixtures/rule-subsets.json').read_text())
        differences=[]
        for case in data['cases']:
            expected={signature(p['cards']):(TYPES[p['type']],key(p,case['level'])) for p in case['expected']}
            actual={signature(m.cards):(m.type,m.key) for m in gen_moves(case['hand'],case['level'])}
            generated = {signature(m.cards):m for m in gen_moves(case['hand'],case['level'])}
            for follow in case['follows']:
                lead = generated[signature(follow['lead']['cards'])]
                replies = gen_moves(case['hand'],case['level'],lead)
                self.assertEqual(replies[0].type,PASS)
                self.assertEqual({signature(m.cards) for m in replies[1:]},
                                 {signature(c) for c in follow['expected']},case['label'])
            for cards in expected.keys()|actual.keys():
                if expected.get(cards)!=actual.get(cards):
                    differences.append(dict(case=case['label'],cards=cards,expected=expected.get(cards),actual=actual.get(cards)))
        self.assertEqual(differences,[],json.dumps(differences[:12],ensure_ascii=False))

if __name__=='__main__': unittest.main()
